[book]
title = "Bril: A Compiler Intermediate Representation for Learning"
authors = ["Adrian Sampson"]
src = "docs"
language = "en"

[output.html]
preferred-dark-theme = "ayu"
curly-quotes = true
git-repository-url = "https://github.com/sampsyo/bril"
site-url = "https://capra.cs.cornell.edu/bril/"
edit-url-template = "https://github.com/sampsyo/bril/edit/main/{path}"
