on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
            node-version: '17'
            cache: 'yarn'
            cache-dependency-path: 'bril-ts/yarn.lock'

      - uses: actions/cache@v2
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'

      - name: Install TypeScript tools
        run: cd bril-ts ; yarn ; yarn build ; yarn link

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril-txt ; flit install --symlink

      - name: Install Turnt
        # run: pip install turnt  # Use instead if pip turnt version >= 1.7
        uses: actions/checkout@v2
        with:
          repository: cucapra/turnt
          path: './turnt'
      - name: Install Turnt part 2
        run: cd turnt ; flit install --symlink


      - name: Problem matcher
        run: echo '::add-matcher::.github/tap-matcher.json'
      - name: Tests
        run: PATH=$PATH:`yarn global bin` make test TURNTARGS=-v

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
            node-version: '17'
            cache: 'yarn'
            cache-dependency-path: 'bril-ts/yarn.lock'

      - uses: actions/cache@v2
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'

      - name: Install TypeScript tools
        run: cd bril-ts ; yarn ; yarn build ; yarn link

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril-txt ; flit install --symlink

      - name: Problem matcher
        run: echo '::add-matcher::.github/brilck-matcher.json'
      - name: brilck
        run: PATH=$PATH:`yarn global bin` make check

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TrueBrain/actions-flake8@master
        with:
          path: bril-txt
